// AUTO-GENERATED by generate.py - do not edit by hand.
window.GALLERY = {
  "comics": [],
  "drawings": [
    {
      "full": "content/Drawings/BirchWardsRiso.jpg",
      "thumb": "content/Drawings/thumbs/BirchWardsRiso.jpg"
    },
    {
      "full": "content/Drawings/Extra Protection for Double Trouble.jpg",
      "thumb": "content/Drawings/thumbs/Extra Protection for Double Trouble.jpg"
    },
    {
      "full": "content/Drawings/Medusamom2.jpg",
      "thumb": "content/Drawings/thumbs/Medusamom2.jpg"
    },
    {
      "full": "content/Drawings/Pissdrawing.jpg",
      "thumb": "content/Drawings/thumbs/Pissdrawing.jpg"
    },
    {
      "full": "content/Drawings/Poppler.jpg",
      "thumb": "content/Drawings/thumbs/Poppler.jpg"
    },
    {
      "full": "content/Drawings/Screamers.jpg",
      "thumb": "content/Drawings/thumbs/Screamers.jpg"
    }
  ],
  "characters": [],
  "storyboards": []
};
window.BOOKS = {
  "comics": [
    {
      "title": "Foxglove",
      "slug": "Foxglove",
      "cover": {
        "full": "content/Comics/Foxglove/Foxglove2.jpg",
        "thumb": "content/Comics/Foxglove/thumbs/Foxglove2.jpg"
      },
      "pages": [
        {
          "full": "content/Comics/Foxglove/Foxglove2.jpg",
          "thumb": "content/Comics/Foxglove/thumbs/Foxglove2.jpg"
        },
        {
          "full": "content/Comics/Foxglove/Foxglove3.jpg",
          "thumb": "content/Comics/Foxglove/thumbs/Foxglove3.jpg"
        },
        {
          "full": "content/Comics/Foxglove/Foxglove4.jpg",
          "thumb": "content/Comics/Foxglove/thumbs/Foxglove4.jpg"
        },
        {
          "full": "content/Comics/Foxglove/Foxglove5.jpg",
          "thumb": "content/Comics/Foxglove/thumbs/Foxglove5.jpg"
        },
        {
          "full": "content/Comics/Foxglove/Foxglove6.jpg",
          "thumb": "content/Comics/Foxglove/thumbs/Foxglove6.jpg"
        },
        {
          "full": "content/Comics/Foxglove/Foxglove7.jpg",
          "thumb": "content/Comics/Foxglove/thumbs/Foxglove7.jpg"
        },
        {
          "full": "content/Comics/Foxglove/Foxglove8.jpg",
          "thumb": "content/Comics/Foxglove/thumbs/Foxglove8.jpg"
        }
      ]
    },
    {
      "title": "Tour",
      "slug": "Tour",
      "cover": {
        "full": "content/Comics/Tour/Tour 0.jpg",
        "thumb": "content/Comics/Tour/thumbs/Tour 0.jpg"
      },
      "pages": [
        {
          "full": "content/Comics/Tour/Tour 0.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 0.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour 1.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 1.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour 2.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 2.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour 2b.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 2b.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour 3.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 3.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour 4.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 4.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour 5.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 5.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour 6.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 6.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour 7.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 7.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour 8.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 8.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_1.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_1.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_10.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_10.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_11.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_11.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_12.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_12.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_13.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_13.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_14.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_14.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_15.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_15.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_2.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_2.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_3.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_3.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_4.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_4.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_5.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_5.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_6.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_6.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_7.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_7.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_8.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_8.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_9.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_9.jpg"
        }
      ]
    },
    {
      "title": "Unboxifying",
      "slug": "Unboxifying",
      "cover": {
        "full": "content/Comics/Unboxifying/page1.png",
        "thumb": "content/Comics/Unboxifying/thumbs/page1.jpg"
      },
      "pages": [
        {
          "full": "content/Comics/Unboxifying/page1.png",
          "thumb": "content/Comics/Unboxifying/thumbs/page1.jpg"
        },
        {
          "full": "content/Comics/Unboxifying/page2.png",
          "thumb": "content/Comics/Unboxifying/thumbs/page2.jpg"
        },
        {
          "full": "content/Comics/Unboxifying/page3.png",
          "thumb": "content/Comics/Unboxifying/thumbs/page3.jpg"
        },
        {
          "full": "content/Comics/Unboxifying/page4.png",
          "thumb": "content/Comics/Unboxifying/thumbs/page4.jpg"
        }
      ]
    }
  ],
  "drawings": [],
  "characters": [],
  "storyboards": []
};
