// AUTO-GENERATED by generate.py - do not edit by hand.
window.GALLERY = {
  "comics": [],
  "drawings": [
    {
      "full": "content/Drawings/BirchWardsRiso.jpg",
      "thumb": "content/Drawings/thumbs/BirchWardsRiso.jpg"
    },
    {
      "full": "content/Drawings/Extra Protection for Double Trouble.jpg",
      "thumb": "content/Drawings/thumbs/Extra Protection for Double Trouble.jpg"
    },
    {
      "full": "content/Drawings/Medusamom2.jpg",
      "thumb": "content/Drawings/thumbs/Medusamom2.jpg"
    },
    {
      "full": "content/Drawings/Pissdrawing.jpg",
      "thumb": "content/Drawings/thumbs/Pissdrawing.jpg"
    },
    {
      "full": "content/Drawings/Poppler.jpg",
      "thumb": "content/Drawings/thumbs/Poppler.jpg"
    },
    {
      "full": "content/Drawings/Screamers.jpg",
      "thumb": "content/Drawings/thumbs/Screamers.jpg"
    }
  ],
  "characters": [],
  "storyboards": []
};
window.BOOKS = {
  "comics": [
    {
      "title": "Tour",
      "slug": "Tour",
      "cover": {
        "full": "content/Comics/Tour/Tour 0.jpg",
        "thumb": "content/Comics/Tour/thumbs/Tour 0.jpg"
      },
      "pages": [
        {
          "full": "content/Comics/Tour/Tour 0.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 0.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour 1.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 1.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour 2.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 2.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour 3.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 3.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour 4.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 4.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour 5.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 5.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour 6.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 6.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour 7.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 7.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour 8.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour 8.jpg"
        }
      ]
    },
    {
      "title": "Unboxifying",
      "slug": "Unboxifying",
      "cover": {
        "full": "content/Comics/Unboxifying/page1.png",
        "thumb": "content/Comics/Unboxifying/thumbs/page1.jpg"
      },
      "pages": [
        {
          "full": "content/Comics/Unboxifying/page1.png",
          "thumb": "content/Comics/Unboxifying/thumbs/page1.jpg"
        },
        {
          "full": "content/Comics/Unboxifying/page2.png",
          "thumb": "content/Comics/Unboxifying/thumbs/page2.jpg"
        },
        {
          "full": "content/Comics/Unboxifying/page3.png",
          "thumb": "content/Comics/Unboxifying/thumbs/page3.jpg"
        },
        {
          "full": "content/Comics/Unboxifying/page4.png",
          "thumb": "content/Comics/Unboxifying/thumbs/page4.jpg"
        }
      ]
    }
  ],
  "drawings": [],
  "characters": [],
  "storyboards": []
};
