// AUTO-GENERATED by generate.py - do not edit by hand.
window.GALLERY = {
  "comics": [],
  "drawings": [
    {
      "full": "content/Drawings/bandanna.jpeg",
      "thumb": "content/Drawings/thumbs/bandanna.jpg"
    },
    {
      "full": "content/Drawings/BirchWardsRiso.jpg",
      "thumb": "content/Drawings/thumbs/BirchWardsRiso.jpg"
    },
    {
      "full": "content/Drawings/Extra Protection for Double Trouble.jpg",
      "thumb": "content/Drawings/thumbs/Extra Protection for Double Trouble.jpg"
    },
    {
      "full": "content/Drawings/Pissdrawing.jpg",
      "thumb": "content/Drawings/thumbs/Pissdrawing.jpg"
    },
    {
      "full": "content/Drawings/Pokerchip.jpg",
      "thumb": "content/Drawings/thumbs/Pokerchip.jpg"
    },
    {
      "full": "content/Drawings/Poppler.jpg",
      "thumb": "content/Drawings/thumbs/Poppler.jpg"
    },
    {
      "full": "content/Drawings/richardsonLogo.png",
      "thumb": "content/Drawings/thumbs/richardsonLogo.jpg"
    },
    {
      "full": "content/Drawings/s-l1600.jpg",
      "thumb": "content/Drawings/thumbs/s-l1600.jpg"
    },
    {
      "full": "content/Drawings/Screamers.jpg",
      "thumb": "content/Drawings/thumbs/Screamers.jpg"
    },
    {
      "full": "content/Drawings/zRosenLogo.jpg",
      "thumb": "content/Drawings/thumbs/zRosenLogo.jpg"
    }
  ],
  "characters": [],
  "storyboards": []
};
window.BOOKS = {
  "comics": [
    {
      "title": "BirchWards",
      "slug": "BirchWards",
      "cover": {
        "full": "content/Comics/BirchWards/WardIssue1SHORTPillage1.jpg",
        "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage1.jpg"
      },
      "pages": [
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage1.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage1.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage2.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage2.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage3.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage3.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage6.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage6.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage7.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage7.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage8.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage8.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage9.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage9.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage10.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage10.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage11.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage11.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage12.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage12.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage13.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage13.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage14.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage14.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage15.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage15.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage16.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage16.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage17.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage17.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage18.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage18.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage19.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage19.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage20.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage20.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage21.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage21.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage22.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage22.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage23.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage23.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage24.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage24.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage25.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage25.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage26.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage26.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage27.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage27.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage28.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage28.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage29.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage29.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage30.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage30.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage35.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage35.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage36.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage36.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage37.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage37.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage38.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage38.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage39.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage39.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage40.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage40.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage41.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage41.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage42.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage42.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage43.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage43.jpg"
        },
        {
          "full": "content/Comics/BirchWards/WardIssue1SHORTPillage48.jpg",
          "thumb": "content/Comics/BirchWards/thumbs/WardIssue1SHORTPillage48.jpg"
        }
      ]
    },
    {
      "title": "Foxglove",
      "slug": "Foxglove",
      "cover": {
        "full": "content/Comics/Foxglove/Foxglove1.jpg",
        "thumb": "content/Comics/Foxglove/thumbs/Foxglove1.jpg"
      },
      "pages": [
        {
          "full": "content/Comics/Foxglove/Foxglove1.jpg",
          "thumb": "content/Comics/Foxglove/thumbs/Foxglove1.jpg"
        },
        {
          "full": "content/Comics/Foxglove/Foxglove2.jpg",
          "thumb": "content/Comics/Foxglove/thumbs/Foxglove2.jpg"
        },
        {
          "full": "content/Comics/Foxglove/Foxglove3.jpg",
          "thumb": "content/Comics/Foxglove/thumbs/Foxglove3.jpg"
        },
        {
          "full": "content/Comics/Foxglove/Foxglove4.jpg",
          "thumb": "content/Comics/Foxglove/thumbs/Foxglove4.jpg"
        },
        {
          "full": "content/Comics/Foxglove/Foxglove5.jpg",
          "thumb": "content/Comics/Foxglove/thumbs/Foxglove5.jpg"
        },
        {
          "full": "content/Comics/Foxglove/Foxglove6.jpg",
          "thumb": "content/Comics/Foxglove/thumbs/Foxglove6.jpg"
        },
        {
          "full": "content/Comics/Foxglove/Foxglove7.jpg",
          "thumb": "content/Comics/Foxglove/thumbs/Foxglove7.jpg"
        },
        {
          "full": "content/Comics/Foxglove/Foxglove8.jpg",
          "thumb": "content/Comics/Foxglove/thumbs/Foxglove8.jpg"
        }
      ]
    },
    {
      "title": "Mire",
      "slug": "Mire",
      "cover": {
        "full": "content/Comics/Mire/Mire_0.jpg",
        "thumb": "content/Comics/Mire/thumbs/Mire_0.jpg"
      },
      "pages": [
        {
          "full": "content/Comics/Mire/Mire_0.jpg",
          "thumb": "content/Comics/Mire/thumbs/Mire_0.jpg"
        },
        {
          "full": "content/Comics/Mire/Mire_1.jpg",
          "thumb": "content/Comics/Mire/thumbs/Mire_1.jpg"
        },
        {
          "full": "content/Comics/Mire/Mire_2.jpg",
          "thumb": "content/Comics/Mire/thumbs/Mire_2.jpg"
        },
        {
          "full": "content/Comics/Mire/Mire_3.jpg",
          "thumb": "content/Comics/Mire/thumbs/Mire_3.jpg"
        },
        {
          "full": "content/Comics/Mire/Mire_4.jpg",
          "thumb": "content/Comics/Mire/thumbs/Mire_4.jpg"
        },
        {
          "full": "content/Comics/Mire/Mire_5.jpg",
          "thumb": "content/Comics/Mire/thumbs/Mire_5.jpg"
        }
      ]
    },
    {
      "title": "Tour",
      "slug": "Tour",
      "cover": {
        "full": "content/Comics/Tour/Tour_0.jpg",
        "thumb": "content/Comics/Tour/thumbs/Tour_0.jpg"
      },
      "pages": [
        {
          "full": "content/Comics/Tour/Tour_0.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_0.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_1.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_1.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_2.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_2.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_3.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_3.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_4.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_4.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_5.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_5.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_6.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_6.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_7.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_7.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_8.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_8.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_9.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_9.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_10.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_10.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_11.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_11.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_12.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_12.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_13.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_13.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_14.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_14.jpg"
        },
        {
          "full": "content/Comics/Tour/Tour_15.jpg",
          "thumb": "content/Comics/Tour/thumbs/Tour_15.jpg"
        }
      ]
    },
    {
      "title": "Unboxifying",
      "slug": "Unboxifying",
      "cover": {
        "full": "content/Comics/Unboxifying/page1.png",
        "thumb": "content/Comics/Unboxifying/thumbs/page1.jpg"
      },
      "pages": [
        {
          "full": "content/Comics/Unboxifying/page1.png",
          "thumb": "content/Comics/Unboxifying/thumbs/page1.jpg"
        },
        {
          "full": "content/Comics/Unboxifying/page2.png",
          "thumb": "content/Comics/Unboxifying/thumbs/page2.jpg"
        },
        {
          "full": "content/Comics/Unboxifying/page3.png",
          "thumb": "content/Comics/Unboxifying/thumbs/page3.jpg"
        },
        {
          "full": "content/Comics/Unboxifying/page4.png",
          "thumb": "content/Comics/Unboxifying/thumbs/page4.jpg"
        }
      ]
    }
  ],
  "drawings": [],
  "characters": [],
  "storyboards": []
};
window.GROUPS = {
  "comics": [],
  "drawings": [
    {
      "base": "chipmunk",
      "images": [
        {
          "full": "content/Drawings/chipmunk_a.jpg",
          "thumb": "content/Drawings/thumbs/chipmunk_a.jpg"
        },
        {
          "full": "content/Drawings/chipmunk_b.jpg",
          "thumb": "content/Drawings/thumbs/chipmunk_b.jpg"
        },
        {
          "full": "content/Drawings/chipmunk_c.jpg",
          "thumb": "content/Drawings/thumbs/chipmunk_c.jpg"
        }
      ]
    },
    {
      "base": "medusamom",
      "images": [
        {
          "full": "content/Drawings/medusaMom_a.jpg",
          "thumb": "content/Drawings/thumbs/medusaMom_a.jpg"
        },
        {
          "full": "content/Drawings/Medusamom_b.jpg",
          "thumb": "content/Drawings/thumbs/Medusamom_b.jpg"
        }
      ]
    },
    {
      "base": "yhivi",
      "images": [
        {
          "full": "content/Drawings/Yhivi_a.jpg",
          "thumb": "content/Drawings/thumbs/Yhivi_a.jpg"
        },
        {
          "full": "content/Drawings/Yhivi_b.jpg",
          "thumb": "content/Drawings/thumbs/Yhivi_b.jpg"
        }
      ]
    }
  ],
  "characters": [],
  "storyboards": []
};
